CREATE TABLE `user` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`email` VARCHAR(255) NULL,
	`password` VARCHAR(255) NULL,
	`username` VARCHAR(255) NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE UNIQUE INDEX `USER_IDX_USERNAME` ON `user`(`username`);
CREATE UNIQUE INDEX `USER_IDX_EMAIL` ON `user` (`email`);

CREATE TABLE `role` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(20) NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;


CREATE TABLE `user_role` (
	`user_id` BIGINT NOT NULL,
	`role_id` BIGINT NOT NULL,
	PRIMARY KEY (`user_id`, `role_id`),
	CONSTRAINT `USER_ROLE_FK1_ROLE` FOREIGN KEY (`role_id`) REFERENCES `role` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `USER_ROLE_FK2_USER` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;
	
CREATE INDEX `USER_ROLE_IDX_ROLE` ON `user_role`(`role_id`);
